"""Lists v2 — Task 11: routing threshold calibration regression test.

Replays a fixture of REAL bge-m3 cosine scores (captured once against the live
Ollama model; see the lists-v2 spec) through the actual ``list_router._decide``,
so it is deterministic and needs no Ollama/DB. It guarantees two things:

  * the CALIBRATED thresholds (match=0.40 / margin=0.04, migration 0055) meet the
    spec's ≥90% routing goal with zero noise-leak; and
  * the original PLACEHOLDER thresholds (0.55 / 0.07) would NOT — so a silent
    revert to the placeholder, or an embedding-document regression that reverts the
    fixture, fails loudly (the DoD's "forces real calibration" guard).

The fixture is regenerated by the calibration script in the spec when the
embedding document format or model changes.
"""
from __future__ import annotations

import json
import pathlib

from backend.services import list_router

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "lists_routing_calibration.json"

CALIBRATED = {"match_threshold": 0.40, "create_threshold": 0.35, "ambiguity_margin": 0.04}
PLACEHOLDER = {"match_threshold": 0.55, "create_threshold": 0.35, "ambiguity_margin": 0.07}


def _load():
    return json.loads(FIXTURE.read_text())


def _scored(item):
    # fixture stores [[name, sim], ...] desc; _decide wants [{id,name,sim}].
    return [{"id": i, "name": n, "sim": s} for i, (n, s) in enumerate(item["scored"])]


def _evaluate(items, cfg):
    """Return (accuracy_over_labeled, misroute, noise_leak, disambiguate)."""
    labeled = [it for it in items if it["expected"] is not None]
    correct = misroute = disamb = noise_leak = 0
    for it in items:
        d = list_router._decide(_scored(it), cfg)
        exp = it["expected"]
        if exp is None:  # noise — must fall back
            if d["action"] != "fallback":
                noise_leak += 1
            continue
        if d["action"] == "match":
            if d["list"]["name"] == exp:
                correct += 1
            else:
                misroute += 1
        elif d["action"] == "disambiguate":
            disamb += 1
            if exp in [c["name"] for c in d["candidates"]]:
                correct += 1  # surfaced to the user with the right option present
            else:
                misroute += 1
        # fallback on a labeled item = a miss (neither correct nor misroute)
    return correct / len(labeled), misroute, noise_leak, disamb


def test_fixture_recommended_matches_calibrated_constants():
    """Guard against the fixture and the shipped thresholds drifting apart."""
    rec = _load()["recommended"]
    assert rec["match_threshold"] == CALIBRATED["match_threshold"]
    assert rec["ambiguity_margin"] == CALIBRATED["ambiguity_margin"]


def test_calibrated_thresholds_meet_routing_goal():
    items = _load()["items"]
    acc, misroute, noise_leak, _ = _evaluate(items, CALIBRATED)
    assert acc >= 0.90, f"routing accuracy {acc:.1%} < 90% goal (R4.3/R4.4)"
    assert noise_leak == 0, f"{noise_leak} noise item(s) wrongly matched a list"
    assert misroute <= 1, f"{misroute} mis-routes (> tolerated 1)"


def test_placeholder_thresholds_would_underperform():
    """Proves calibration was necessary: the 0.55/0.07 placeholder misses the goal.
    If this ever passes, the embedding document (and thus the fixture) regressed."""
    items = _load()["items"]
    acc, _, _, _ = _evaluate(items, PLACEHOLDER)
    assert acc < 0.90, (
        f"placeholder thresholds scored {acc:.1%} — fixture/document may have "
        "regressed; recalibrate via the spec's calibration script")
