-- 0022 — Finance categorization overhaul: schema for the precedence cascade.
--
-- Owned-object DDL → authored for the elevated bowershub_migrator role (the
-- C7 cutover is live: bowershub_migrator = LOGIN SUPERUSER, MIGRATION_DB_USER
-- wired, 0021 applied). A non-owner could not ALTER finance.transactions /
-- recreate public.transactions — that is exactly the 2026-06-19 crash class.
-- New finance.* objects auto-grant DML to bowershub_app / SELECT to
-- finance_reader via the 0021 default-privilege mirror. Applies from empty (C2).
--
-- Refs: .kiro/specs/finance-categorization (Task 2; R1.2, R1.3, R1.4, R2.1,
-- R2.5, R2.6, R6.2). Seed data + config defaults live in 0023.

-- 1. Merchant directory (R1.2). One row per normalized merchant; merchant-level
--    embedding backs the kNN tier (R2.3) — far fewer vectors than per-txn.
CREATE TABLE IF NOT EXISTS finance.merchants (
    merchant_key      text PRIMARY KEY,
    display_name      text,
    category_prior_id integer REFERENCES finance.categories(id),
    mcc               text,
    domain            text,
    embedding         public.halfvec(1024),
    embedding_version integer,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS merchants_embedding_idx ON finance.merchants
    USING hnsw (embedding public.halfvec_cosine_ops)
    WHERE (embedding IS NOT NULL);

-- 2. Normalization rules (R1.1/R1.4) — DB-driven; replaces the hardcoded prompt
--    rules block and the NL→category map.
CREATE TABLE IF NOT EXISTS finance.normalization_rules (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_type   text    NOT NULL,           -- 'prefix_strip' | 'regex_replace' | 'suffix_strip' | 'collapse'
    pattern     text    NOT NULL,
    replacement text    NOT NULL DEFAULT '',
    priority    integer NOT NULL DEFAULT 100,
    is_active   boolean NOT NULL DEFAULT true,
    version     integer NOT NULL DEFAULT 1,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- 3. MCC → category map (R1.3) — cold-start prior.
CREATE TABLE IF NOT EXISTS finance.mcc_categories (
    mcc         text PRIMARY KEY,
    category_id integer NOT NULL REFERENCES finance.categories(id),
    description text
);

-- 4. User rules (R2.1) — user-orderable priority, first-match-wins, amount ranges.
CREATE TABLE IF NOT EXISTS finance.user_rules (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority          integer NOT NULL DEFAULT 100,
    merchant_key      text,
    description_regex text,
    amount_min        numeric(12,2),
    amount_max        numeric(12,2),
    account_id        character varying(128) REFERENCES finance.accounts(id),
    category_id       integer NOT NULL REFERENCES finance.categories(id),
    is_active         boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS user_rules_priority_idx ON finance.user_rules (priority) WHERE is_active;

-- 5. Merchant memory (R3.1) — the deterministic learned store; keyed on the
--    normalized merchant (replaces the 0018 first-word trigger, dropped in Task 7).
CREATE TABLE IF NOT EXISTS finance.merchant_memory (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_key       text    NOT NULL,
    category_id        integer NOT NULL REFERENCES finance.categories(id),
    times_reinforced   integer NOT NULL DEFAULT 1,
    last_reinforced_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (merchant_key, category_id)
);

-- 6. Provenance / decision log (R2.6/R5.6) — append-only; AUTHORITATIVE for
--    coverage/LLM-call metrics and the review-queue rationale. prior_category_id
--    makes every auto-write reversible.
CREATE TABLE IF NOT EXISTS finance.categorization_decision (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      character varying(128) NOT NULL,
    tier                text    NOT NULL,        -- transfer|rule|merchant_memory|embedding_knn|llm
    confidence          numeric(5,4),
    model_id            text,
    prior_category_id   integer,
    applied_category_id integer,
    is_transfer_set     boolean NOT NULL DEFAULT false,
    auto_applied        boolean NOT NULL DEFAULT false,
    rationale           jsonb,
    decided_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS categorization_decision_txn_idx
    ON finance.categorization_decision (transaction_id, decided_at DESC);

-- 7. Eval labels (R2.7) — hand-verified pairs incl. transfer/debt cases.
CREATE TABLE IF NOT EXISTS finance.eval_labels (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description          text    NOT NULL,
    account_type         text,
    amount               numeric(12,2),
    expected_category_id integer REFERENCES finance.categories(id),
    is_transfer_expected boolean NOT NULL DEFAULT false,
    notes                text
);

-- 8. Config (R2.5 thresholds, rollout feature-gate, kNN sizing) — key/value,
--    mirroring the bh_platform_settings / embedding_config pattern. Defaults in 0023.
CREATE TABLE IF NOT EXISTS finance.categorizer_config (
    key        text PRIMARY KEY,
    value      jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- 9. Additive, nullable columns (safest ALTER class — no table rewrite).
ALTER TABLE finance.transactions ADD COLUMN IF NOT EXISTS merchant_key text;               -- R1.1 link
ALTER TABLE finance.transactions ADD COLUMN IF NOT EXISTS categorized_by_tier text;        -- R2.6 denormalized current decision
ALTER TABLE finance.transactions ADD COLUMN IF NOT EXISTS categorization_confidence numeric(5,4);
CREATE INDEX IF NOT EXISTS transactions_merchant_key_idx ON finance.transactions (merchant_key);
ALTER TABLE finance.accounts ADD COLUMN IF NOT EXISTS account_type text;                   -- R6.2 prerequisite (checking|savings|credit_card|loan|mortgage|brokerage)
ALTER TABLE finance.categories ADD COLUMN IF NOT EXISTS embedding public.halfvec(1024);    -- B2 cold-start kNN fallback

-- 10. Extend public.transactions (the migrator-owned view that crash-looped on
--     2026-06-19). Mirrors 0016 plus the new columns + account_type. Recreated
--     here under the migrator role so ownership stays correct.
DROP VIEW IF EXISTS public.transactions;
CREATE VIEW public.transactions AS
SELECT
    t.id,
    t.account_id,
    a.account_name,
    a.account_type,
    t.posted_date,
    t.amount,
    t.description,
    t.memo,
    t.pending,
    t.category_id,
    c.name AS category_name,
    t.merchant_key,
    t.categorized_by_tier,
    t.categorization_confidence,
    t.user_category_override,
    t.is_transfer,
    t.is_transfer_manual,
    t.house_tag,
    t.house_tag_manual,
    t.created_at,
    t.updated_at,
    t.source,
    t.is_investment
FROM finance.transactions t
LEFT JOIN finance.categories c ON c.id = t.category_id
LEFT JOIN finance.accounts a ON a.id = t.account_id;

GRANT SELECT ON public.transactions TO finance_reader;
