"""
Branding router (R2.1, R2.2, R2.4, R2.5, R2.6, R2.7, R2.8).

Thin HTTP layer over `backend.services.branding_store`. The store handles
all of the disk + DB work; this module only translates between FastAPI's
multipart/form-data uploads and the store's `bytes` API, applies RBAC,
emits audit log entries, and maps the store's typed exceptions onto HTTP
status codes.

Status code mapping:
    IconValidationError with a size-rule error  -> 413 Payload Too Large
    IconValidationError otherwise               -> 400 Bad Request
    RollbackUnavailable                         -> 409 Conflict

The corresponding `/icons/*` static mount and the dynamic `/manifest.json`
handler live in `backend.main` (see comments there).
"""

from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile

from backend.middleware.audit import AuditLogger
from backend.middleware.auth import get_current_user, require_admin
from backend.services import branding_store
from backend.services.branding_store import (
    FieldError,
    IconValidationError,
    RollbackUnavailable,
)


router = APIRouter(prefix="/api/branding", tags=["branding"])


def _serialize_field_errors(errors: list[FieldError]) -> list[dict]:
    return [{"field": e.field, "message": e.message} for e in errors]


def _client_ip(request: Request) -> Optional[str]:
    return request.client.host if request.client else None


@router.get("/icon")
async def get_icon(user: dict = Depends(get_current_user)):
    """
    Return the active icon manifest for the UI (R2.1).

    Available to any authenticated user — the icon is part of the app
    chrome that every user sees.
    """
    return await branding_store.get_manifest()


@router.post("/icon")
async def upload_icon(
    request: Request,
    file: UploadFile = File(...),
    user: dict = Depends(require_admin),
):
    """
    Upload a new active app icon (R2.2, R2.4, R2.5, R2.7, R2.8).

    Body is `multipart/form-data` with the PNG bytes under the field
    name ``file``. The branding store validates, generates the 192px
    and maskable-512px variants, atomically swaps the new set into
    ``/files/branding/active/``, archives the previous active set into
    the rollback slot, and bumps the cache-busting version string in
    `bh_platform_settings`.
    """
    file_bytes = await file.read()

    try:
        result = await branding_store.upload_icon(file_bytes)
    except IconValidationError as e:
        # Size-rule violations get the HTTP-413 treatment; every other
        # validation failure (mime/dim/aspect/decode) is a 400. A single
        # upload can fail multiple rules at once — return all of them.
        size_violation = any(err.field == "size" for err in e.errors)
        status_code = 413 if size_violation else 400
        raise HTTPException(
            status_code=status_code,
            detail={"errors": _serialize_field_errors(e.errors)},
        )

    await AuditLogger.log(
        user_id=user["id"],
        action="branding_icon_upload",
        target_type="branding",
        target_id=None,
        details={
            "version": result["version"],
            "filename": file.filename,
            "size_bytes": len(file_bytes),
        },
        ip_address=_client_ip(request),
    )
    return result


@router.post("/icon/revert-to-default")
async def revert_to_default(
    request: Request,
    user: dict = Depends(require_admin),
):
    """
    Restore the built-in icon set generated by ``scripts/generate_icons.py``
    and bump the manifest version (R2.6, R2.8). Preserves the rollback
    slot so the admin can still undo to whatever icon was active before
    the most recent upload, even after reverting.
    """
    result = await branding_store.revert_to_default()
    await AuditLogger.log(
        user_id=user["id"],
        action="branding_icon_revert",
        target_type="branding",
        target_id=None,
        details={"version": result["version"]},
        ip_address=_client_ip(request),
    )
    return result


@router.post("/icon/rollback")
async def rollback_icon(
    request: Request,
    user: dict = Depends(require_admin),
):
    """
    Swap the active icon set with the previous one (R2.7, R2.8). Returns
    409 if no rollback slot is populated.
    """
    try:
        result = await branding_store.rollback()
    except RollbackUnavailable as e:
        raise HTTPException(status_code=409, detail=str(e))

    await AuditLogger.log(
        user_id=user["id"],
        action="branding_icon_rollback",
        target_type="branding",
        target_id=None,
        details={"version": result["version"]},
        ip_address=_client_ip(request),
    )
    return result
